// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_nY0P0IQJid6KOkwLBYzSPZshBfDX5l4',
    appId: '1:374352474830:web:b61a268196d8f7d982d69f',
    messagingSenderId: '374352474830',
    projectId: 'volunteersigniiner',
    authDomain: 'volunteersigniiner.firebaseapp.com',
    storageBucket: 'volunteersigniiner.appspot.com',
    measurementId: 'G-G5T734VWZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmhvePsbU4fsq425tO7M6VTz7Eq5mQ26A',
    appId: '1:374352474830:android:fcd47abff2fbfeb882d69f',
    messagingSenderId: '374352474830',
    projectId: 'volunteersigniiner',
    storageBucket: 'volunteersigniiner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVqAgnpOvWysoTN6mvCxC57qzm2lktH9c',
    appId: '1:374352474830:ios:7443ee36968805ff82d69f',
    messagingSenderId: '374352474830',
    projectId: 'volunteersigniiner',
    storageBucket: 'volunteersigniiner.appspot.com',
    iosClientId: '374352474830-qmbc5jvnl188trfpo2f89qt4su2lhuet.apps.googleusercontent.com',
    iosBundleId: 'com.example.volunteerSigniinerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVqAgnpOvWysoTN6mvCxC57qzm2lktH9c',
    appId: '1:374352474830:ios:7443ee36968805ff82d69f',
    messagingSenderId: '374352474830',
    projectId: 'volunteersigniiner',
    storageBucket: 'volunteersigniiner.appspot.com',
    iosClientId: '374352474830-qmbc5jvnl188trfpo2f89qt4su2lhuet.apps.googleusercontent.com',
    iosBundleId: 'com.example.volunteerSigniinerFlutter',
  );
}
